### ISSUE TITLE
[Bug]: Token error

### ISSUE THREAD

**Issue by evan-neres** [ismaelOrtega14/node-red-contrib-firebase-cloud-messaging#22]
### What happened?

Error sending notification 
	-{"error":{"code":400,"message":"The registration token is not a valid FCM registration token","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.firebase.fcm.v1.FcmError","errorCode":"INVALID_ARGUMENT"}]}}

### How to reproduce?

On trigger

### Plugin Version

2.0.0

### Node.js Version

20.18.0

### NPM Version

10.8.2

### Node-RED Version

4.0.5

### What hardware are you seeing the problem on?

Other Linux

**Comment by ismaelOrtega14** [comment]
Hello!
I need more information to see what is happening in this case.
At first sight it seems that the device token you introduced is not valid.

Can you export a flow to see how are you using the node?
Be carefull and don't send any sensitive data

**Comment by ismaelOrtega14** [comment]
Due to lack of more information this issue will be closed
